services:
  continuwuity:
    build: .
    container_name: continuwuity
    restart: unless-stopped
    volumes:
      - continuwuity_data:/var/lib/conduwuit

volumes:
  continuwuity_data:

networks:
  proxy:
    external: true
